/* ═══════════════════════════════════════════════════════════
   РЕАЛЬНОЕ МЕНЮ ПАНЛАБ
   Источник: карточка заведения в Яндекс Еде, снято 31.07.2026
   https://eda.yandex.ru/r/panlab_phobo_bao_tom_yam_restaurant

   Названия, цены, граммовки, калорийность, метка «Острое» и фото —
   с Яндекса, без правок.
   Описания (desc) Яндекс на карточках не отдаёт — написаны нами,
   их нужно согласовать с заказчиком. См. README.
   ═══════════════════════════════════════════════════════════ */

const CATS = [
  { id:'soup',   name:'Супы',        ya:'Супы' },
  { id:'bao',    name:'Бао',         ya:'Бао' },
  { id:'wok',    name:'Вок',         ya:'Вок' },
  { id:'sushi',  name:'Суширитто',   ya:'Суширитто' },
  { id:'snack',  name:'Закуски',     ya:'Горячие закуски|Закуски|Гедза и дамплинги' },
  { id:'burger', name:'Бургеры',     ya:'Бургеры' },
  { id:'pizza',  name:'Пицца',       ya:'Пицца' },
  { id:'dessert',name:'Десерты',     ya:'Десерты' },
  { id:'drink',  name:'Напитки',     ya:'Холодные напитки' },
  { id:'sauce',  name:'Соусы',       ya:'Соусы' }
];

/* hot — метка «Острое» с Яндекса. hit — по рейтингу Яндекса.
   veg — проставлено нами по составу, требует подтверждения заказчика. */
const MENU = [
  // ── Супы ──────────────────────────────────────────────
  { cat:'soup', name:'ФоБо (0,5 л)', price:699, weight:'500 г', kcal:320, rating:'77% (26)', hit:true,
    desc:'Классический вьетнамский суп на говяжьем бульоне: рисовая лапша, слайсы говядины, зелень, лайм.',
    img:'assets/menu/fobo-05.jpeg' },
  { cat:'soup', name:'ФоБо (0,7 л)', price:899, weight:'700 г', kcal:427,
    desc:'Тот же ФоБо, только объёмнее — когда одной порции точно мало.',
    img:'assets/menu/fobo-07.jpeg' },
  { cat:'soup', name:'ФоБо (1 л)', price:1199, weight:'1 кг', kcal:580,
    desc:'Литровый ФоБо. Хватит на двоих или на очень голодного одного.',
    img:'assets/menu/fobo-1.jpeg' },
  { cat:'soup', name:'ФоБо (Бульон)', price:249, weight:'250 г', kcal:63,
    desc:'Чистый говяжий бульон, который варится часами. Основа всего меню.',
    img:'assets/menu/fobo-bulon.jpeg' },
  { cat:'soup', name:'ФоГа (0,5 л)', price:699, weight:'500 г', kcal:310,
    desc:'Куриная версия фо: лёгкий бульон, рисовая лапша, филе, зелёный лук и кинза.',
    img:'assets/menu/foga-05.jpeg' },
  { cat:'soup', name:'ФоГа (0,7 л)', price:899, weight:'700 г', kcal:420,
    desc:'Куриный фо в увеличенной порции.',
    img:'assets/menu/foga-07.jpeg' },
  { cat:'soup', name:'ФоГа (1 л)', price:1199, weight:'1 кг', kcal:580,
    desc:'Литр куриного фо — большая порция на компанию.',
    img:'assets/menu/foga-1.jpeg' },
  { cat:'soup', name:'ФоТом (0,5 л)', price:699, weight:'500 г', kcal:270,
    desc:'Гибрид фо и том яма: кисло-острый бульон с рисовой лапшой.',
    img:'assets/menu/fotom-05.jpeg' },
  { cat:'soup', name:'ФоТом (0,7 л)', price:899, weight:'700 г', kcal:350,
    desc:'ФоТом в увеличенной порции.',
    img:'assets/menu/fotom-07.jpeg' },
  { cat:'soup', name:'ФоТом (1 л)', price:1199, weight:'1 кг', kcal:480,
    desc:'Литровый ФоТом.',
    img:'assets/menu/fotom-1.jpeg' },
  { cat:'soup', name:'Том Ям (Креветка-кальмар)', price:899, weight:'600 г', kcal:450, hot:true, hit:true,
    desc:'Кокосовое молоко, лемонграсс, галангал, креветки и кальмар. Тот самый острый.',
    img:'assets/menu/tomyam-krevetka.jpeg' },
  { cat:'soup', name:'Том Ям (Курица)', price:799, weight:'600 г', kcal:462, hot:true,
    desc:'Том ям на курином филе — мягче по вкусу, но так же ароматно и остро.',
    img:'assets/menu/tomyam-kurica.jpeg' },
  { cat:'soup', name:'Мисо суп', price:449, weight:'350 г', kcal:116, light:true,
    desc:'Лёгкий японский суп с мисо-пастой, тофу и водорослями вакамэ.',
    img:'assets/menu/miso.jpeg' },
  { cat:'soup', name:'Кимчи (суп)', price:499, weight:'400 г', kcal:192, rating:'75% (4)',
    desc:'Корейский суп на основе кимчи из пекинской капусты.',
    img:'assets/menu/kimchi.jpeg' },
  { cat:'soup', name:'Кимчи от шефа', price:599, weight:'400 г', kcal:312, hot:true, light:true,
    desc:'Авторская версия кимчи-супа от шефа. Заметно острее базовой.',
    img:'assets/menu/kimchi-shef.jpeg' },

  // ── Бао ───────────────────────────────────────────────
  { cat:'bao', name:'Бао с курицей', price:449, weight:'220 г', kcal:442, rating:'100% (10)', hit:true,
    desc:'Паровая булочка с куриным филе, свежими овощами и фирменным соусом.',
    img:'assets/menu/bao-kurica.jpeg' },
  { cat:'bao', name:'Бао Курица Спайси', price:449, weight:'245 г', kcal:527, rating:'75% (16)',
    desc:'Курица в остром соусе спайси, огурец и зелень в паровой булочке.',
    img:'assets/menu/bao-kurica-spicy.jpeg' },
  { cat:'bao', name:'Бао с говядиной и трюфельным соусом', price:549, weight:'220 г', kcal:438,
    desc:'Томлёная говядина с трюфельным соусом — самый насыщенный бао в меню.',
    img:'assets/menu/bao-govyadina.jpeg' },
  { cat:'bao', name:'Бао со свининой по-корейски', price:449, weight:'245 г', kcal:598, rating:'100% (6)',
    desc:'Свинина в корейском маринаде, маринованные овощи, кунжут.',
    img:'assets/menu/bao-svinina.jpeg' },
  { cat:'bao', name:'Бао Том-ям с королевской креветкой', price:599, weight:'220 г', kcal:403,
    desc:'Королевская креветка с соусом на основе том яма.',
    img:'assets/menu/bao-tomyam-krevetka.jpeg' },
  { cat:'bao', name:'Бао Том-Ям с курицей', price:499, weight:'200 г', kcal:390,
    desc:'Курица с кисло-острым соусом том ям в паровой булочке.',
    img:'assets/menu/bao-tomyam-kurica.jpeg' },
  { cat:'bao', name:'Бао «Сливочный Краб»', price:499, weight:'240 г', kcal:456, rating:'80% (5)',
    desc:'Крабовая начинка со сливочным соусом и свежим огурцом.',
    img:'assets/menu/bao-krab.jpeg' },
  { cat:'bao', name:'Бао с овощами', price:399, weight:'175 г', kcal:343, veg:true,
    desc:'Вегетарианский бао: обжаренные овощи, зелень, соус.',
    img:'assets/menu/bao-ovoshi.jpeg' },
  { cat:'bao', name:'Бань Бао', price:99, weight:'110 г', kcal:297,
    desc:'Классическая паровая булочка без начинки — к супу или соусу.',
    img:'assets/menu/ban-bao.jpeg' },

  // ── Вок ───────────────────────────────────────────────
  { cat:'wok', name:'Wok лапша Удон собери сам', price:599, weight:'400 г', kcal:556, rating:'94% (18)', hit:true,
    desc:'Пшеничная лапша удон: сами выбираете начинку и соус.',
    img:'assets/menu/wok-udon.jpeg' },
  { cat:'wok', name:'Wok лапша фунчоза собери сам', price:599, weight:'400 г', kcal:556,
    desc:'Стеклянная лапша фунчоза с начинкой и соусом на ваш выбор.',
    img:'assets/menu/wok-funchoza.jpeg' },
  { cat:'wok', name:'Wok Лапша «Соба» — собери сам', price:599, weight:'400 г', kcal:556,
    desc:'Гречневая лапша соба: начинка и соус на выбор.',
    img:'assets/menu/wok-soba.jpeg' },
  { cat:'wok', name:'Wok Рис «Наси-горенг» с креветкой и курицей', price:799, weight:'460 г', kcal:626, rating:'75% (8)',
    desc:'Индонезийский жареный рис с креветкой, курицей и овощами.',
    img:'assets/menu/wok-nasi-goreng.jpeg' },

  // ── Суширитто ─────────────────────────────────────────
  { cat:'sushi', name:'Суширитто «Курица-Спайси»', price:599, weight:'330 г', kcal:611, rating:'83% (6)',
    desc:'Ролл размером с буррито: курица в остром соусе, рис, овощи, нори.',
    img:'assets/menu/sushirito-kurica.jpeg' },
  { cat:'sushi', name:'Суширитто «Овощной»', price:499, weight:'300 г', kcal:549, veg:true,
    desc:'Вегетарианский суширитто: рис, свежие овощи, авокадо, нори.',
    img:'assets/menu/sushirito-ovoshnoy.jpeg' },
  { cat:'sushi', name:'Суширитто с тигровой креветкой', price:899, weight:'330 г', kcal:611,
    desc:'Тигровая креветка, рис, овощи и соус в большом ролле.',
    img:'assets/menu/sushirito-krevetka.jpeg' },

  // ── Закуски ───────────────────────────────────────────
  { cat:'snack', name:'Гёдзе со свининой', price:999, weight:'200 г', kcal:450,
    desc:'Обжаренные японские пельмешки со свининой и капустой, соус понзу.',
    img:'assets/menu/gedze.jpeg' },
  { cat:'snack', name:'Нэм Ран (3 шт)', price:599, weight:'175 г', kcal:245,
    desc:'Вьетнамские хрустящие роллы, обжаренные во фритюре. Три штуки.',
    img:'assets/menu/nem-ran.jpeg' },
  { cat:'snack', name:'Креветки в тесте Харумаки жареные', price:999, weight:'190 г', kcal:420, rating:'100% (3)', hit:true,
    desc:'Креветки в хрустящем тесте харумаки, обжаренные до золотистой корочки.',
    img:'assets/menu/harumaki.jpeg' },
  { cat:'snack', name:'Баклажаны в кисло-сладком соусе', price:499, weight:'240 г', kcal:360, veg:true,
    desc:'Обжаренные баклажаны в кисло-сладком соусе с кунжутом.',
    img:'assets/menu/baklazhany.jpeg' },
  { cat:'snack', name:'Сырные палочки в панировке', price:499, weight:'150 г', kcal:513, rating:'75% (4)',
    desc:'Сырные палочки в хрустящей панировке. Подаём с соусом.',
    img:'assets/menu/syrnye-palochki.jpeg' },
  { cat:'snack', name:'Луковые кольца в панировке', price:399, weight:'150 г', kcal:458,
    desc:'Луковые кольца во фритюре — классика к пиву.',
    img:'assets/menu/lukovye-kolca.jpeg' },
  { cat:'snack', name:'Картофельные дольки', price:399, weight:'150 г', kcal:354,
    desc:'Картофельные дольки со специями, запечённые до румяной корочки.',
    img:'assets/menu/kartofelnye-dolki.jpeg' },
  { cat:'snack', name:'Картофель фри', price:349, weight:'150 г', kcal:336,
    desc:'Классический картофель фри.',
    img:'assets/menu/kartofel-fri.jpeg' },
  { cat:'snack', name:'Микс закусок к пиву', price:1599, weight:'500 г',
    desc:'Большая тарелка на компанию: всё лучшее из горячих закусок сразу.',
    img:'assets/menu/miks-zakusok.jpeg' },
  { cat:'snack', name:'Битые огурцы с соусом', price:399, weight:'165 г', kcal:196, veg:true,
    desc:'Хрустящие битые огурцы с чесночно-соевой заправкой.',
    img:'assets/menu/bitye-ogurcy.jpeg' },
  { cat:'snack', name:'Маринованные огурцы', price:149, weight:'100 г', kcal:40, veg:true,
    desc:'Маринованные огурцы — простая закуска к крепкому.',
    img:'assets/menu/marinovannye-ogurcy.jpeg' },

  // ── Бургеры ───────────────────────────────────────────
  { cat:'burger', name:'«Крабсбургер»', price:799, weight:'370 г', kcal:807,
    desc:'Бургер с крабовой котлетой и сливочным соусом.',
    img:'assets/menu/krabsburger.jpeg' },
  { cat:'burger', name:'Бао Бургер «Чикен Спайси»', price:699, weight:'300 г', kcal:549,
    desc:'Бургер на паровой булочке бао: курица в остром соусе спайси.',
    img:'assets/menu/bao-burger-spicy.jpeg' },
  { cat:'burger', name:'Бао Бургер «Чикен Пин-ап»', price:799, weight:'370 г', kcal:673,
    desc:'Бао-бургер с курицей, овощами и фирменным соусом «Пин-ап».',
    img:'assets/menu/bao-burger-pinap.jpeg' },

  // ── Пицца ─────────────────────────────────────────────
  { cat:'pizza', name:'Пицца Пепперони', price:899, weight:'350 г', kcal:714,
    desc:'Томатный соус, моцарелла, пепперони.',
    img:'assets/menu/pizza-pepperoni.jpeg' },
  { cat:'pizza', name:'Пицца 4 сыра', price:899, weight:'335 г', kcal:757,
    desc:'Четыре вида сыра на сливочной основе.',
    img:'assets/menu/pizza-4-syra.jpeg' },
  { cat:'pizza', name:'Пицца Мясная', price:899, weight:'400 г', kcal:856,
    desc:'Мясное ассорти, томатный соус, моцарелла.',
    img:'assets/menu/pizza-myasnaya.jpeg' },
  { cat:'pizza', name:'Пицца Маргарита', price:899, weight:'390 г', kcal:737, veg:true,
    desc:'Томатный соус, моцарелла, базилик. Классика.',
    img:'assets/menu/pizza-margarita.jpeg' },

  // ── Десерты ───────────────────────────────────────────
  { cat:'dessert', name:'Бананы жареные', price:499, weight:'150 г', kcal:258, rating:'100% (3)', hit:true,
    desc:'Бананы во фритюре с карамельной корочкой — азиатская классика.',
    img:'assets/menu/banany.jpeg' },
  { cat:'dessert', name:'Чизкейк карамельный', price:399, weight:'100 г',
    desc:'Чизкейк с солёной карамелью.',
    img:'assets/menu/chizkeyk-karamel.jpeg' },
  { cat:'dessert', name:'Чизкейк классический (ванильный)', price:399, weight:'100 г',
    desc:'Классический ванильный чизкейк на песочной основе.',
    img:'assets/menu/chizkeyk-vanil.jpeg' },
  { cat:'dessert', name:'Чизкейк шоколадный', price:399, weight:'100 г', rating:'100% (3)',
    desc:'Шоколадный чизкейк с насыщенным какао-вкусом.',
    img:'assets/menu/chizkeyk-shokolad.jpeg' },
  { cat:'dessert', name:'Чизкейк манго-маракуйя', price:399, weight:'100 г',
    desc:'Чизкейк с тропическим муссом манго и маракуйи.',
    img:'assets/menu/chizkeyk-mango.jpeg' },

  // ── Напитки ───────────────────────────────────────────
  { cat:'drink', name:'Лимонад «Имбирно-малиновый»', price:500, weight:'450 мл',
    desc:'Домашний лимонад: имбирь, малина, лайм.',
    img:'assets/menu/limonad-imbir.jpeg' },
  { cat:'drink', name:'Лимонад «Цветочно-тропический»', price:500, weight:'450 мл',
    desc:'Тропические фрукты с цветочными нотами.',
    img:'assets/menu/limonad-tropik.jpeg' },
  { cat:'drink', name:'Лимонад «Перечно-цветочный»', price:500, weight:'450 мл',
    desc:'Неожиданное сочетание розового перца и цветочного сиропа.',
    img:'assets/menu/limonad-perec.jpeg' },
  { cat:'drink', name:'Лимонад «Грейпфрут-личи»', price:500, weight:'450 мл',
    desc:'Горьковатый грейпфрут и сладкое личи.',
    img:'assets/menu/limonad-greypfrut.jpeg' },
  { cat:'drink', name:'Лимонад «Пряная сладость»', price:500, weight:'450 мл',
    desc:'Пряный лимонад со специями — согревает даже холодным.',
    img:'assets/menu/limonad-pryanyy.jpeg' },
  { cat:'drink', name:'Пиво Non-Alco «Glitcher Brainstorm APA»', price:750, weight:'500 мл',
    desc:'Безалкогольный APA с выраженной хмелевой горчинкой.',
    img:'' },
  { cat:'drink', name:'Пиво Non-Alco «Maisels Weisse»', price:750, weight:'500 мл',
    desc:'Безалкогольное немецкое пшеничное.',
    img:'' },
  { cat:'drink', name:'Сок (1 л)', price:650, weight:'1 л',
    desc:'Сок в ассортименте, литровая упаковка.',
    img:'' },
  { cat:'drink', name:'Вода (газ/негаз.)', price:300, weight:'500 мл',
    desc:'Питьевая вода, с газом или без.',
    img:'' },
  { cat:'drink', name:'Тоник (ж/б)', price:300, weight:'330 мл',
    desc:'Тоник в банке.',
    img:'' },
  { cat:'drink', name:'Кола (ж/б)', price:300, weight:'330 мл',
    desc:'Кола в банке.',
    img:'' },

  // ── Соусы ─────────────────────────────────────────────
  { cat:'sauce', name:'Соус Том ям', price:99, weight:'30 г', kcal:90,
    desc:'Кисло-острый соус на основе том яма.', img:'' },
  { cat:'sauce', name:'Соус Спайси', price:99, weight:'30 г', kcal:143, hot:true,
    desc:'Острый соус спайси.', img:'' },
  { cat:'sauce', name:'Соус соевый чесночно-кунжутный', price:99, weight:'30 г', kcal:59,
    desc:'Соевый соус с чесноком и кунжутом.', img:'' },
  { cat:'sauce', name:'Соус Бао', price:99, weight:'30 г', kcal:150,
    desc:'Фирменный соус к паровым булочкам бао.', img:'' },
  { cat:'sauce', name:'Соус Ранч', price:99, weight:'30 г', kcal:153,
    desc:'Сливочный соус ранч.', img:'' }
];
